appenders:
  console:
    kind: console
    encoder:
      pattern: "{h({d(%Y-%m-%d %H:%M:%S)(utc)} - {l}: {m}{n})}"
loggers:
  preagonal_client_rs:
    level: debug
    appenders:
      - console
    additive: false
root:
  level: warn
  appenders:
    - console