[discord]
token = "[CHANGEME]"
channel_id = "[CHANGEME]"
server_id = "[CHANGEME]"

[[clients]]
# The server IP
host = "[CHANGEME]"
# The server port
port = 12345
# The client type
client_type = { RemoteControl = { version = "GSERV025", npc_control = { version = "NCL21075" } } }
# The login information
login = { auth = { account_name = "[CHANGEME]", password = "[CHANGEME]", identification = ["win", "[CHANGEME]", "[CHANGEME]", "[CHANGEME]"] } }

[[clients]]
# The server IP
host = "[CHANGEME]"
# The server port
port = 12345
# The client type
client_type = { Game = { version = "G3D2204D", header_format = "EILLLT", encryption_keys = { rsa_private_key = """
-----BEGIN PRIVATE KEY-----
[CHANGEME]
-----END PRIVATE KEY-----
""" } } }
# The login information
login = { nick = "GB", auth = { account_name = "[CHANGEME]", "password" = "[CHANGEME]", identification = ["win", "[CHANGEME]", "[CHANGEME]", "[CHANGEME]"] } }